version: "3.5"
services:
  server:
    build:
      context: .
      args:
        EXAMPLE_ARG: 'example argument'
    environment:
        EXAMPLE_ENV: 'Changed environment value'
        PASSWORD: password
    volumes:
      - ./Data:/home/rstudio/Data:ro
      - ./Result:/home/rstudio/Results:ro
    ports:
      - 8787:8787