version: "3.5"
services:
  server:
    build:
      context: .
      args:
        EXAMPLE_ARG: 'example argument'
    environment:
        EXAMPLE_ENV: 'Changed environment value'
        PASSWORD: password
    volumes:
      - ./Data:/home/rstudio/Data:rw
      - ./Data:/home/rstudio/Data/Bed-Seq:rw
      - ./Results:/home/rstudio/Results:rw
    ports:
      - 8787:8787