version: "3.6"
services:
  server:
    build: .
    image: martindi/eqtldetector
    environment:
        PASSWORD: password
    volumes:
      - ./Bed-Seq:/home/rstudio/Bed-Seq:rw
      - ./Results:/home/rstudio/Results:rw
      - ./Results/bamstat:/home/rstudio/Results/bamstat:rw
      - ./Results/mbv:/home/rstudio/Results/mbv:rw
      - ./Results/quan:/home/rstudio/Results/quan:rw
      - ./Results/pca:/home/rstudio/Results/pca:rw
      - ./Results/cis_nominal:/home/rstudio/Results/cis_nominal:rw
      - ./Results/cis_permutation:/home/rstudio/Results/cis_permutation:rw
      - ./Results/trans:/home/rstudio/Results/trans:rw
      - ./Results/fdensity:/home/rstudio/Results/fdensity:rw
      - ./Results/fenrich:/home/rstudio/Results/fenrich:rw
      - ./Results/rtc:/home/rstudio/Results/rtc:rw
    ports:
      - 8787:8787
