version: "3.6"
services:
  server:
    build: .
    image: martindi/eqtldetector
    environment:
        PASSWORD: password
    volumes:
      - ./Bed-Seq:/home/rstudio/Bed-Seq:rw
      - ./Results:/home/rstudio/Results:rw
      - ./Results/bamstat:/home/rstudio/Results/bamstat:rw
      - ./Results/mbv:/home/rstudio/Results/mbv:rw
      - ./Results/quan:/home/rstudio/Results/quan:rw
      - ./Results/pca:/home/rstudio/Results/pca:rw
      - ./Results/cis_nominal:/home/rstudio/Results/cis_nominal:rw
    ports:
      - 8787:8787
