#installing EMMA for phylogenetic cofounder analysis
install.packages("emma")
#Genomic tools intallation
install.packages("BiocManager")
library(BiocManager)
install("snpStats", ask = FALSE)
library(snpStats)
install("GenomicTools", ask = FALSE)
install.packages("glue")
install.packages("knitr")
install.packages("rmarkdown")
install.packages("kableExtra")
install.packages("XML")
install.packages("rlist")
install.packages("readr")
